### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by cxddlmu**
change the class definition way of MagicGrid

### CODE REVIEW

**Comment by e-oj** [comment]
Based on [this template](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html) I think it might work if you leave the "declare" statement and add an "export" statement like:

```javascript
export = MagicGrid

declare class MagicGrid { .... }
```

Try that. If it works then update this PR, else I'll merge as is. Let me know how it goes.

**Comment by cxddlmu** [comment]
sorry for updating late.
i have tried your suggestion. It works. But you should remove export in below code, because export assignment can not be used with other export
`export interface MagicGridProps`

**Comment by cxddlmu** [comment]
this below change will better solution
export default MagicGrid
declare class MagicGrid { .... }

**Comment by hk-skit** [comment]
Hi @e-oj, 

Can you please merge this PR? This change required for magic-grid to work with the angular eco-system.

**Pull request merged**
