### PR TITLE
Removed jQuery + Switched to rollup

### PR DESCRIPTION
**Pull request by imlinus**
Hi,

I have removed the jQuery dependency, and I have switched from webpack to rollup.

Rollup is for libs, webpack is for apps ;-)

Cheers,
Linus

### CODE REVIEW

**Comment by imlinus** [comment]
Oh, plus I've used the https://standardjs.com style-guide for clean code 👍

**Comment by e-oj** [comment]
Great Work 👍 👍. I'll take out the ready function in grid.html because I want the test file to be as simple as possible. Thanks for the plug on rollup as well, I didn't even know it existed.

**Comment by e-oj** [comment]
Let me know once you're done with the Vue.js port so I can add a link to it in the readme

**Comment by e-oj** [comment]
@imlinus Upgrade to the new version and see if that fixes the initial rendering issues

**Comment by imlinus** [comment]
Hey, https://github.com/imlinus/Vue-Magic-Grid, works smooth like butter for me!

**Pull request merged**
